// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddComponentElementConfig = { compilerOnly: boolean };

export type CompatVisitorConfig = {
  /**
   * @internal
   */
  target: 'LEPUS' | 'JS' | 'MIXED';
  /**
   * @public
   */
  componentsPkg: Array<string>;
  /**
   * @public
   */
  oldRuntimePkg: Array<string>;
  /**
   * @public
   */
  newRuntimePkg: string;
  /**
   * @public
   */
  additionalComponentAttributes: Array<string>;
  /**
   * @public
   */
  addComponentElement: boolean | AddComponentElementConfig;
  /**
   * @public
   * @deprecated
   */
  simplifyCtorLikeReactLynx2: boolean;
  /**
   * @public
   * @deprecated
   */
  removeComponentAttrRegex: string | null;
  /**
   * @public
   */
  disableDeprecatedWarning: boolean;
  /**
   * @public
   * @deprecated
   */
  darkMode?: DarkModeConfig | boolean;
};

export type DarkModeConfig = { themeExpr: string };
