# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  # Make less review comments
  collapse_walkthrough: true
  sequence_diagrams: false

  # Summary
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"

  # Labeling
  # auto_apply_labels: true
  labeling_instructions:
    - label: "platform:Web"
      instructions: |
        Apply when the PR contains changes to either
          - `./packages/web-platform/**`
          - `./packages/webpack/template-webpack-plugin/src/WebEncodePlugin.ts`
        Or when the linked issue has lable "platform:Web"
    - label: "framework:React"
      instructions: |
        Apply when the PR contains changes to either
          - `./packages/react/**`
          - `./packages/rspeedy/plugin-react/**`
          - `./packages/rspeedy/plugin-react-alias/**`
          - `./packages/webpack/react-webpack-plugin/**`
        Or when the linked issue has lable "framework:React"
