# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[files]
extend-exclude = [
  "**/*.snap",
  "**/*.snap.txt",
  "**/*/CHANGELOG.md",
  "pnpm-lock.yaml",
  "biome.jsonc",
  "packages/web-platform/web-explorer/preinstalled/homepage.json",
  "packages/web-platform/web-tests/tests/web-elements/performance/react-dom.production.min.js",
]

[default.extend-words]
childs = "childs"
styl = "styl"
aci = "aci"
nd = "nd"
