packages:
  - .github/actions/eco-ci
  - examples/*
  - packages/react
  - packages/react/refresh
  - packages/react/runtime
  - packages/react/transform
  - packages/react/worklet-runtime
  - packages/rspeedy/*
  - packages/tools/*
  - packages/web-platform/*
  - packages/webpack/*
  - packages/third-party/*
  - website

# Default catalogs
catalog:
  "@microsoft/api-extractor": "7.51.1"

catalogs:
  # Rsbuild monorepo packages
  rsbuild:
    "@rsbuild/core": "1.2.19"
    "@rsbuild/webpack": "1.2.3"
    "@rsbuild/plugin-less": "1.1.1"
    "@rsbuild/plugin-sass": "1.3.1"
    "@rsbuild/plugin-webpack-swc": "1.0.12"

  # Rspack monorepo packages
  rspack:
    "@rspack/cli": "1.3.0-beta.1"
    "@rspack/core": "1.3.0-beta.1"
    "@rspack/test-tools": "1.3.0-beta.1"

overrides:
  "@rspack/core": "$@rspack/core"
  "@rsbuild/core>@rspack/core": "$@rspack/core"

patchedDependencies:
  "@napi-rs/cli@2.18.4": "patches/@napi-rs__cli@2.18.4.patch"
  "@rollup/plugin-typescript": "patches/@rollup__plugin-typescript.patch"

onlyBuiltDependencies:
  - dprint

ignoredBuiltDependencies:
  - core-js
