packages:
  - examples/*
  - packages/background-only
  - packages/react
  - packages/react/refresh
  - packages/react/runtime
  - packages/react/testing-library
  - packages/react/transform
  - packages/react/worklet-runtime
  - packages/rspeedy/*
  - packages/testing-library/*
  - packages/testing-library/examples/*
  - packages/third-party/*
  - packages/tools/*
  - packages/use-sync-external-store
  - packages/web-platform/*
  - packages/webpack/*
  - website

# Default catalogs
catalog:
  "@microsoft/api-extractor": "7.52.8"

catalogs:
  # Rsbuild monorepo packages
  rsbuild:
    "@rsbuild/core": "1.4.5"

  # Rspack monorepo packages
  rspack:
    "@rspack/cli": "1.4.5"
    "@rspack/core": "1.4.5"
    "@rspack/test-tools": "1.4.5"

overrides:
  "@rspack/core": "$@rspack/core"
  "@rsbuild/core>@rspack/core": "$@rspack/core"
  "path-serializer": "^0.5.0"

patchedDependencies:
  "@napi-rs/cli@2.18.4": "patches/@napi-rs__cli@2.18.4.patch"
  "@rollup/plugin-typescript": "patches/@rollup__plugin-typescript.patch"

strictDepBuilds: true

onlyBuiltDependencies:
  - dprint
  - esbuild
  - wasm-pack

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@swc/core"
  - core-js
  - unrs-resolver
