packages:
  - examples/*
  - packages/background-only
  - packages/react
  - packages/react/refresh
  - packages/react/runtime
  - packages/react/testing-library
  - packages/react/transform
  - packages/react/worklet-runtime
  - packages/rspeedy/*
  - packages/testing-library/*
  - packages/testing-library/examples/*
  - packages/third-party/*
  - packages/tools/*
  - packages/use-sync-external-store
  - packages/web-platform/*
  - packages/webpack/*
  - website

configDependencies:
  "@pnpm/plugin-better-defaults": 0.1.0+sha512-aWj7Jv9NcNs/OoazrxP6QspLgKRZ2PHj6wPris6ZCEqmXw+Z8zK59KLzl9NBFGRCO4PNA9pwDWLu+8N3NiqUAQ==
  "@pnpm/plugin-trusted-deps": 0.1.0+sha512-OK05vSZpezQHcS7Y0T5A25QXDbBRtRq52s76eOkMgp9v8ifNrIR8pjIGqrUFUn0PwKLt2i+U1LPYB+RWi1xjaQ==

# ReactLynx testing library needs this
# TODO: remove hoist
hoistPattern:
  - "@lynx-js/react"
  - "preact"

# Default catalogs
catalog:
  "@microsoft/api-extractor": "7.52.10"

catalogs:
  # Rsbuild monorepo packages
  rsbuild:
    "@rsbuild/core": "1.4.13"

  # Rspack monorepo packages
  rspack:
    "@rspack/cli": "1.4.11"
    "@rspack/core": "1.4.11"
    "@rspack/test-tools": "1.4.11"

overrides:
  "@rspack/core": "$@rspack/core"
  "@rsbuild/core>@rspack/core": "$@rspack/core"

patchedDependencies:
  "@napi-rs/cli@2.18.4": "patches/@napi-rs__cli@2.18.4.patch"
  "@rollup/plugin-typescript": "patches/@rollup__plugin-typescript.patch"
  "webpack@5.101.0": patches/webpack@5.101.0.patch

# Avoid the `Error: Cannot find module 'typescript'` error when using `enableGlobalVirtualStore: true`
# See: https://pnpm.io/settings#enableglobalvirtualstore
packageExtensions:
  ts-patch:
    peerDependencies:
      typescript: "*"

strictDepBuilds: true

onlyBuiltDependencies:
  - dprint
  - esbuild

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@swc/core"
  - core-js
  - unrs-resolver
