packages:
  - examples/*
  - packages/react
  - packages/react/refresh
  - packages/react/runtime
  - packages/react/transform
  - packages/react/worklet-runtime
  - packages/react/testing-library
  - packages/rspeedy/*
  - packages/tools/*
  - packages/web-platform/*
  - packages/webpack/*
  - packages/third-party/*
  - packages/testing-library/*
  - packages/testing-library/examples/*
  - packages/background-only
  - "!packages/testing-library/examples"
  - website
catalog:
  "@microsoft/api-extractor": 7.52.8
catalogs:
  rsbuild:
    "@rsbuild/core": 1.3.21
    "@rsbuild/webpack": 1.3.2
    "@rsbuild/plugin-less": 1.2.4
    "@rsbuild/plugin-sass": 1.3.1
    "@rsbuild/plugin-webpack-swc": 1.1.1
  rspack:
    "@rspack/cli": 1.3.11
    "@rspack/core": 1.3.11
    "@rspack/test-tools": 1.3.11
ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - dprint
  - esbuild
overrides:
  "@rspack/core": $@rspack/core
  "@rsbuild/core>@rspack/core": $@rspack/core
