packages:
  - benchmark/react
  - examples/*
  - packages/background-only
  - packages/lynx/*
  - packages/react
  - packages/react/refresh
  - packages/react/runtime
  - packages/react/testing-library
  - packages/react/transform
  - packages/react/worklet-runtime
  - packages/rspeedy/*
  - packages/testing-library/*
  - packages/testing-library/examples/*
  - packages/third-party/*
  - packages/tools/*
  - packages/use-sync-external-store
  - packages/web-platform/*
  - packages/webpack/*
  - website

catalog:
  "@microsoft/api-extractor": 7.52.11

catalogs:
  rsbuild:
    "@rsbuild/core": 1.5.4
  rspack:
    "@rspack/cli": 1.5.2
    "@rspack/core": 1.5.2
    "@rspack/test-tools": 1.5.2

enablePrePostScripts: false

ignorePatchFailures: false

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - unrs-resolver

onlyBuiltDependencies:
  - dprint
  - esbuild

optimisticRepeatInstall: true

overrides:
  "@rsbuild/core>@rspack/core": $@rspack/core
  "@rspack/core": $@rspack/core

patchedDependencies:
  "@napi-rs/cli@2.18.4": patches/@napi-rs__cli@2.18.4.patch
  "@rollup/plugin-typescript": patches/@rollup__plugin-typescript.patch
  "@upupming/preact": patches/@upupming__preact.patch

resolutionMode: lowest-direct

strictDepBuilds: true
