[package]
name = "web-style-transformer"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
inline-style-parser = { path = "../inline-style-parser" }
js-sys = { workspace = true }
lazy_static = { workspace = true }
wasm-bindgen = { workspace = true }
