/*
 * Copyright 2025 The Lynx Authors. All rights reserved.
 * Licensed under the Apache License Version 2.0 that can be found in the
 * LICENSE file in the root directory of this source tree.
 */

use fnv::{FnvHashMap, FnvHashSet};

pub const CSS_ID_ATTRIBUTE: &str = "l-css-id";
pub const LYNX_ENTRY_NAME_ATTRIBUTE: &str = "l-e-name";

#[cfg(feature = "client")]
pub const LYNX_UNIQUE_ID_ATTRIBUTE: &str = "l-uid";
#[cfg(feature = "client")]
pub const LYNX_TEMPLATE_MEMBER_ID_ATTRIBUTE: &str = "l-t-e-id";
#[cfg(feature = "client")]
pub const APPEAR_EVENT_NAME: &str = "appear";
#[cfg(feature = "client")]
pub const DISAPPEAR_EVENT_NAME: &str = "disappear";
#[cfg(feature = "client")]
pub const LYNX_EXPOSURE_ID_ATTRIBUTE: &str = "exposure-id"; // if this attribute is present, the exposure event is enabled
#[cfg(feature = "client")]
pub const LYNX_TIMING_FLAG_ATTRIBUTE: &str = "__lynx_timing_flag"; // if this attribute is present, we should collect timing flags on creating and send it on calling __flushElementTree
#[cfg(feature = "client")]
pub(crate) const STYLE_PROPERTY_MAP: &[&str] = &[
  "",
  "top",
  "left",
  "right",
  "bottom",
  "position",
  "box-sizing",
  "background-color",
  "border-left-color",
  "border-right-color",
  "border-top-color",
  "border-bottom-color",
  "border-radius",
  "border-top-left-radius",
  "border-bottom-left-radius",
  "border-top-right-radius",
  "border-bottom-right-radius",
  "border-width",
  "border-left-width",
  "border-right-width",
  "border-top-width",
  "border-bottom-width",
  "color",
  "opacity",
  "display",
  "overflow",
  "height",
  "width",
  "max-width",
  "min-width",
  "max-height",
  "min-height",
  "padding",
  "padding-left",
  "padding-right",
  "padding-top",
  "padding-bottom",
  "margin",
  "margin-left",
  "margin-right",
  "margin-top",
  "margin-bottom",
  "white-space",
  "letter-spacing",
  "text-align",
  "line-height",
  "text-overflow",
  "font-size",
  "font-weight",
  "flex",
  "flex-grow",
  "flex-shrink",
  "flex-basis",
  "flex-direction",
  "flex-wrap",
  "align-items",
  "align-self",
  "align-content",
  "justify-content",
  "background",
  "border-color",
  "font-family",
  "font-style",
  "transform",
  "animation",
  "animation-name",
  "animation-duration",
  "animation-timing-function",
  "animation-delay",
  "animation-iteration-count",
  "animation-direction",
  "animation-fill-mode",
  "animation-play-state",
  "line-spacing",
  "border-style",
  "order",
  "box-shadow",
  "transform-origin",
  "linear-orientation",
  "linear-weight-sum",
  "linear-weight",
  "linear-gravity",
  "linear-layout-gravity",
  "layout-animation-create-duration",
  "layout-animation-create-timing-function",
  "layout-animation-create-delay",
  "layout-animation-create-property",
  "layout-animation-delete-duration",
  "layout-animation-delete-timing-function",
  "layout-animation-delete-delay",
  "layout-animation-delete-property",
  "layout-animation-update-duration",
  "layout-animation-update-timing-function",
  "layout-animation-update-delay",
  "adapt-font-size",
  "aspect-ratio",
  "text-decoration",
  "text-shadow",
  "background-image",
  "background-position",
  "background-origin",
  "background-repeat",
  "background-size",
  "border",
  "visibility",
  "border-right",
  "border-left",
  "border-top",
  "border-bottom",
  "transition",
  "transition-property",
  "transition-duration",
  "transition-delay",
  "transition-timing-function",
  "content",
  "border-left-style",
  "border-right-style",
  "border-top-style",
  "border-bottom-style",
  "implicit-animation",
  "overflow-x",
  "overflow-y",
  "word-break",
  "background-clip",
  "outline",
  "outline-color",
  "outline-style",
  "outline-width",
  "vertical-align",
  "caret-color",
  "direction",
  "relative-id",
  "relative-align-top",
  "relative-align-right",
  "relative-align-bottom",
  "relative-align-left",
  "relative-top-of",
  "relative-right-of",
  "relative-bottom-of",
  "relative-left-of",
  "relative-layout-once",
  "relative-center",
  "enter-transition-name",
  "exit-transition-name",
  "pause-transition-name",
  "resume-transition-name",
  "flex-flow",
  "z-index",
  "text-decoration-color",
  "linear-cross-gravity",
  "margin-inline-start",
  "margin-inline-end",
  "padding-inline-start",
  "padding-inline-end",
  "border-inline-start-color",
  "border-inline-end-color",
  "border-inline-start-width",
  "border-inline-end-width",
  "border-inline-start-style",
  "border-inline-end-style",
  "border-start-start-radius",
  "border-end-start-radius",
  "border-start-end-radius",
  "border-end-end-radius",
  "relative-align-inline-start",
  "relative-align-inline-end",
  "relative-inline-start-of",
  "relative-inline-end-of",
  "inset-inline-start",
  "inset-inline-end",
  "mask-image",
  "grid-template-columns",
  "grid-template-rows",
  "grid-auto-columns",
  "grid-auto-rows",
  "grid-column-span",
  "grid-row-span",
  "grid-column-start",
  "grid-column-end",
  "grid-row-start",
  "grid-row-end",
  "grid-column-gap",
  "grid-row-gap",
  "justify-items",
  "justify-self",
  "grid-auto-flow",
  "filter",
  "list-main-axis-gap",
  "list-cross-axis-gap",
  "linear-direction",
  "perspective",
  "cursor",
  "text-indent",
  "clip-path",
  "text-stroke",
  "text-stroke-width",
  "text-stroke-color",
  "-x-auto-font-size",
  "-x-auto-font-size-preset-sizes",
  "mask",
  "mask-repeat",
  "mask-position",
  "mask-clip",
  "mask-origin",
  "mask-size",
  "gap",
  "column-gap",
  "row-gap",
  "image-rendering",
  "hyphens",
  "-x-app-region",
  "-x-animation-color-interpolation",
  "-x-handle-color",
  "-x-handle-size",
  "offset-path",
  "offset-distance",
];

lazy_static::lazy_static! {
  pub static ref LYNX_TAG_TO_HTML_TAG_MAP: FnvHashMap<&'static str, &'static str> = FnvHashMap::from_iter(vec![
    ("view", "x-view"),
    ("text", "x-text"),
    ("image", "x-image"),
    ("raw-text", "raw-text"),
    ("scroll-view", "x-scroll-view"),
    ("wrapper", "lynx-wrapper"),
    ("list", "x-list"),
    ("page", "div"),
  ]);

  pub static ref HTML_TAG_TO_LYNX_TAG_MAP: FnvHashMap<&'static str, &'static str> = FnvHashMap::from_iter(LYNX_TAG_TO_HTML_TAG_MAP
    .iter()
    .map(|(k, v)| (*v, *k))
  );

  /**
   * See packages/web-platform/web-core-wasm/ts/client/webElementsDynamicLoader.ts
   * This is a replica of the map in  packages/web-platform/web-core-wasm/ts/constants.ts
   */
  pub static ref LYNX_TAG_TO_DYNAMIC_LOAD_TAG_ID: FnvHashMap<&'static str, usize> = FnvHashMap::from_iter(vec![
    ("list", 0),
    ("x-swiper", 1),
    ("x-input", 2),
    ("x-input-ng", 2),
    ("input", 2),
    ("x-textarea", 3),
    ("x-audio-tt", 4),
    ("x-foldview-ng", 5),
    ("x-foldview-header-ng", 5),
    ("x-foldview-slot-drag-ng", 5),
    ("x-foldview-slot-ng", 5),
    ("x-foldview-toolbar-ng", 5),
    ("x-refresh-view", 6),
    ("x-refresh-header", 6),
    ("x-refresh-footer", 6),
    ("x-overlay-ng", 7),
    ("x-viewpager-ng", 8),
    ("x-viewpager-item-ng", 8),
  ]);

  pub static ref ALREADY_LOADED_TAGS: FnvHashSet<&'static str> = FnvHashSet::from_iter(vec![
    "view",
    "text",
    "image",
    "raw-text",
    "scroll-view",
    "wrapper",
    "div",
    "svg"
  ]);
}
