// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const FONTTOOLS_VERSION = '4.59.0';
const pythonCommand = process.env.GENUI_PYTHON
  ?? (process.platform === 'win32' ? 'python' : 'python3');
const SOURCE_FONT_SHA256 =
  '9acca321fb0119b66ee722ab200f6ad4693ea777efb88e62ec564d90443b5b2f';
const SUBSET_FONT_SHA256 =
  '0e01ffc7951222b5e902dd2eccaa0bed79b1641156e205e9605fb439e288b423';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const openuiDir = path.resolve(scriptDir, '..');
const sourceCssPath = path.resolve(
  openuiDir,
  '../a2ui/styles/material-icons.css',
);
const outputCssPath = path.resolve(openuiDir, 'styles/material-icons.css');
const ligatureManifestPath = path.resolve(
  scriptDir,
  'material-icon-ligatures.txt',
);

const ligatures = fs.readFileSync(ligatureManifestPath, 'utf8')
  .split(/\r?\n/)
  .filter(Boolean);

assertManifestMatchesSources(ligatures);

const glyphAliases = { location_on: 'place' };
const glyphs = ligatures.map((name) => glyphAliases[name] ?? name);
const subsetFlags = [
  '--layout-features=rlig',
  '--no-layout-closure',
  '--glyph-names',
];
const sourceFont = readEmbeddedFont(sourceCssPath);
assertHash(sourceFont, SOURCE_FONT_SHA256, 'source font');
const subsetInputSha256 = sha256(Buffer.from([
  `fonttools=${FONTTOOLS_VERSION}`,
  `source-font=${SOURCE_FONT_SHA256}`,
  `ligatures=${ligatures.join(',')}`,
  `glyphs=${glyphs.join(',')}`,
  `flags=${subsetFlags.join(',')}`,
].join('\n')));

if (process.argv.includes('--check')) {
  const subsetFont = readEmbeddedFont(outputCssPath);
  assertHash(subsetFont, SUBSET_FONT_SHA256, 'subset font');
  assertSubsetInputHash(outputCssPath, subsetInputSha256);
  console.log(
    `[openui] Verified ${ligatures.length} icon ligatures and the embedded font hash.`,
  );
} else {
  const temporaryDir = fs.mkdtempSync(
    path.join(os.tmpdir(), 'genui-openui-material-icons-'),
  );
  const sourceFontPath = path.join(temporaryDir, 'source.ttf');
  const subsetFontPath = path.join(temporaryDir, 'subset.ttf');
  fs.writeFileSync(sourceFontPath, sourceFont);

  try {
    const actualFontToolsVersion = run(
      pythonCommand,
      ['-c', 'import fontTools; print(fontTools.__version__)'],
      `Install Python and FontTools with \`python3 -m pip install fonttools==${FONTTOOLS_VERSION}\`, or set GENUI_PYTHON to that Python interpreter.`,
    ).trim();
    if (actualFontToolsVersion !== FONTTOOLS_VERSION) {
      throw new Error(
        `Expected FontTools ${FONTTOOLS_VERSION}, but ${pythonCommand} provides ${actualFontToolsVersion}. `
          + 'Use GENUI_PYTHON to select the pinned Python environment.',
      );
    }

    run(
      pythonCommand,
      [
        '-m',
        'fontTools.subset',
        sourceFontPath,
        `--text-file=${ligatureManifestPath}`,
        `--glyphs=${glyphs.join(',')}`,
        ...subsetFlags,
        `--output-file=${subsetFontPath}`,
      ],
      `Install Python and FontTools with \`python3 -m pip install fonttools==${FONTTOOLS_VERSION}\`, or set GENUI_PYTHON to that Python interpreter.`,
    );

    const subsetFont = fs.readFileSync(subsetFontPath);
    assertHash(subsetFont, SUBSET_FONT_SHA256, 'subset font');
    assertLigaturesShapeIdentically(sourceFontPath, subsetFontPath, ligatures);

    const outputCss = `/*
 * Material Symbols subset used by the built-in OpenUI components.
 * Generated by \`pnpm --filter @lynx-js/genui-openui generate:material-icons\`;
 * do not edit directly.
 * Subset input SHA-256: ${subsetInputSha256}
 */
@font-face {
  font-family: "Material Icons Round";
  src: url("data:font/ttf;base64,${subsetFont.toString('base64')}")
    format("truetype");
}
`;
    fs.writeFileSync(outputCssPath, outputCss);

    console.log(
      `[openui] Wrote ${outputCssPath} (${sourceFont.length} -> ${subsetFont.length} font bytes).`,
    );
  } finally {
    fs.rmSync(temporaryDir, { recursive: true, force: true });
  }
}

function assertManifestMatchesSources(manifest) {
  const iconSourcePath = path.resolve(
    openuiDir,
    'src/catalog/Icon/index.tsx',
  );
  const iconSource = fs.readFileSync(iconSourcePath, 'utf8');
  const iconNamesSource = iconSource.match(
    /const ICON_NAMES = \[([\s\S]*?)\] as const;/,
  )?.[1];
  if (!iconNamesSource) {
    throw new Error(`Could not read ICON_NAMES from ${iconSourcePath}.`);
  }

  const names = [...iconNamesSource.matchAll(/'([a-z0-9][a-z0-9_]*)'/g)]
    .map((match) => match[1]);
  const extraConsumers = [
    ['src/catalog/AudioPlayer/index.tsx', 'music_note'],
    ['src/catalog/Video/index.tsx', 'play_arrow'],
  ];
  for (const [relativePath, name] of extraConsumers) {
    const sourcePath = path.resolve(openuiDir, relativePath);
    const source = fs.readFileSync(sourcePath, 'utf8');
    if (!source.includes(`>${name}<`)) {
      throw new Error(`Could not find ${name} in ${sourcePath}.`);
    }
    names.push(name);
  }

  const expected = [...new Set(names)].sort();
  const actual = [...new Set(manifest)].sort();
  if (expected.join('\n') !== actual.join('\n')) {
    throw new Error(
      `Update ${ligatureManifestPath} to match the OpenUI icon consumers.\n`
        + `Expected:\n${expected.join('\n')}\nActual:\n${actual.join('\n')}`,
    );
  }
}

function assertLigaturesShapeIdentically(sourcePath, subsetPath, names) {
  for (const name of names) {
    const sourceShape = shape(sourcePath, name);
    const subsetShape = shape(subsetPath, name);
    if (sourceShape !== subsetShape) {
      throw new Error(
        `The ${name} ligature changed shape: ${sourceShape} -> ${subsetShape}.`,
      );
    }
  }
}

function shape(fontPath, text) {
  const output = run(
    'hb-shape',
    [fontPath, text, '--features=rlig'],
    'Install the HarfBuzz CLI (https://harfbuzz.github.io/) and retry. On macOS, run `brew install harfbuzz`.',
  ).trim();
  const match = output.match(/^\[([^=|]+)=[^+|]+\+(-?\d+)\]$/);
  if (!match || match[1] === '.notdef' || match[1] === 'gid0') {
    throw new Error(`${text} did not shape to one glyph: ${output}`);
  }
  return output;
}

function run(command, args, missingCommandHint) {
  try {
    return execFileSync(command, args, { encoding: 'utf8', stdio: 'pipe' });
  } catch (error) {
    if (error.code === 'ENOENT') {
      throw new Error(`Missing ${command}. ${missingCommandHint}`);
    }
    if (error.stderr) process.stderr.write(error.stderr);
    throw error;
  }
}

function readEmbeddedFont(cssPath) {
  const css = fs.readFileSync(cssPath, 'utf8');
  const base64 = css.match(/data:font\/ttf;base64,([A-Za-z0-9+/=]+)/)?.[1];
  if (!base64) {
    throw new Error(`Could not find the embedded TTF in ${cssPath}.`);
  }
  return Buffer.from(base64, 'base64');
}

function assertSubsetInputHash(cssPath, expected) {
  const css = fs.readFileSync(cssPath, 'utf8');
  const actual = css.match(/Subset input SHA-256: ([a-f0-9]{64})/)?.[1];
  if (actual !== expected) {
    throw new Error(
      `The generated font inputs changed (${
        actual ?? 'missing'
      } -> ${expected}). `
        + 'Run the material icon generator and review the new subset.',
    );
  }
}

function assertHash(contents, expected, label) {
  const actual = sha256(contents);
  if (actual !== expected) {
    throw new Error(
      `Unexpected ${label} SHA-256: ${actual}. Expected ${expected}. `
        + 'If the icon set changed intentionally, review the generated font and update its pinned hash.',
    );
  }
}

function sha256(contents) {
  return createHash('sha256').update(contents).digest('hex');
}
