/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DirectiveDceVisitorConfig {
  /** @internal */
  target: 'LEPUS' | 'JS' | 'MIXED'
}
/** @internal */
export interface ElementTemplateAsset {
  /** @internal */
  templateId: string
  /** @internal */
  compiledTemplate: unknown
  /** @internal */
  sourceFile: string
}
/** @internal */
export interface JsxTransformerConfig {
  /** @internal */
  preserveJsx: boolean
  /** @internal */
  runtimePkg: string
  /** @internal */
  jsxImportSource?: string
  /** @internal */
  filename: string
  /** @internal */
  target: 'LEPUS' | 'JS' | 'MIXED'
  /** @internal */
  isDynamicComponent?: boolean
}
export interface TransformNodiffBundleOptions {
  filename: string
  pluginName: string
  sourceFileName?: string
  sourcemap: boolean | string
  extractStr: boolean | ExtractStrConfig
  minify?: boolean
}
export interface TransformNodiffBundleOutput {
  code: string
  map?: string
  selectStrVec?: Array<string>
  useWorklet?: boolean
  errors: Array<PartialMessage>
  warnings: Array<PartialMessage>
}
/**
 * This is esbuild's PartialMessage definition.
 * https://github.com/evanw/esbuild/blob/043ab306c490f692c68e8d254bbf00b6468be87d/lib/shared/types.ts#L421
 */
export interface PartialMessage {
  id?: string
  pluginName?: string
  text?: string
  location?: PartialLocation
  notes?: Array<PartialNote>
  detail?: string
}
export interface PartialNote {
  text?: string
  location?: PartialLocation
}
export interface PartialLocation {
  file?: string
  namespace?: string
  line?: number
  column?: number
  length?: number
  lineText?: string
  suggestion?: string
}
/**
 * {@inheritdoc PluginReactLynxOptions.extractStr}
 * @public
 */
export interface ExtractStrConfig {
  /**
   * @public
   * The minimum length of string literals to be extracted.
   *
   * @remarks
   * Default value: `20`.
   *
   * @example
   *
   * ```js
   * import { defineConfig } from '@lynx-js/rspeedy'
   * import { pluginReactLynx } from '@lynx-js/react-rsbuild-plugin'
   *
   * export default defineConfig({
   *   plugins: [
   *     pluginReactLynx({
   *       extractStr: {
   *         strLength: 10,
   *       },
   *     })
   *   ],
   * })
   * ```
   */
  strLength: number
  /** @internal */
  extractedStrArr?: Array<string>
}
export interface RefreshVisitorConfig {
  library?: Array<string>
}
export interface TransformNodiffOptions {
  /**
   * @internal
   * This is used internally to make sure the test output is consistent.
   */
  mode?: 'production' | 'development' | 'test'
  pluginName: string
  filename: string
  sourceFileName?: string
  sourcemap: boolean | string
  sourceMapColumns?: boolean
  inlineSourcesContent?: boolean
  /**
   * @public
   * This is swc syntax config in JSON format
   */
  syntaxConfig?: string
  isModule?: boolean | 'unknown'
  cssScope: boolean | CSSScopeVisitorConfig
  snapshot?: boolean | SnapshotJSXTransformerConfig
  elementTemplate?: boolean | ElementTemplateTransformerConfig
  engineVersion?: string
  shake: boolean | ShakeVisitorConfig
  compat: boolean | CompatVisitorConfig
  refresh: boolean | RefreshVisitorConfig
  defineDCE: boolean | DefineDCEVisitorConfig
  directiveDCE: boolean | DirectiveDCEVisitorConfig
  worklet: boolean | WorkletVisitorConfig
  dynamicImport?: boolean | DynamicImportVisitorConfig
  /** @internal */
  inject?: boolean | InjectVisitorConfig
  inputSourceMap?: string
}
export interface UiSourceMapRecord {
  uiSourceMap: number
  filename: string
  lineNumber: number
  columnNumber: number
  snapshotId?: string
}
export interface TransformNodiffOutput {
  code: string
  map?: string
  errors: Array<PartialMessage>
  warnings: Array<PartialMessage>
  uiSourceMapRecords: Array<UiSourceMapRecord>
  /** @internal */
  elementTemplates?: Array<ElementTemplateAsset>
}
export function transformReactLynxSync(code: string, options?: TransformNodiffOptions | undefined | null): TransformNodiffOutput
export function transformReactLynx(code: string, options?: TransformNodiffOptions | undefined | null): Promise<TransformNodiffOutput>
export function transformBundleResultSync(code: string, options?: TransformNodiffBundleOptions | undefined | null): TransformNodiffBundleOutput
export function transformBundleResult(code: string, options?: TransformNodiffBundleOptions | undefined | null): Promise<TransformNodiffBundleOutput>
