name: After Test

# SECURITY WARNING:
# Workflows triggered by workflow_run event run in the context of the base branch, making it safe to access repository secrets
# Handle sensitive information like CODECOV_TOKEN and RELATIVE_CI_KEY with care to prevent exposure to untrusted code

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  bundle-analysis:
    uses: ./.github/workflows/workflow-test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
    with:
      runs-on: lynx-ubuntu-24.04-medium
      run: |
        pnpm --filter @lynx-js/example-react run build
        pnpm --filter @lynx-js/example-react -c exec 'pnpm --package=@relative-ci/agent dlx relative-ci-agent'
        pnpm --filter @lynx-js/web-explorer run build
        pnpm --filter @lynx-js/web-explorer -c exec 'pnpm --package=@relative-ci/agent dlx relative-ci-agent'
