name: NodeJS Dependencies
"on":
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - pnpm-lock.yaml
      - "**/package.json"
  merge_group:
    types: [checks_requested]

# Set minimum permissions to prevent unnecessary access
permissions: {}

env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  sherif:
    runs-on: lynx-ubuntu-24.04-medium
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: "24"
          package-manager-cache: false
      - run: |
          pnpm dedupe --check
          pnpm dlx sherif@latest
