name: pre-code-review-check

on:
  pull_request:
    branches: ["main"]
env:
  CI: 1
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_REF: ${{ github.ref }}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  code-style-check:
    runs-on: lynx-ubuntu-24.04-medium
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: prepare-env
        run: |
          npm install -g corepack@latest
          corepack enable
          pnpm install --frozen-lockfile
      - name: check code style
        run: |
          pnpm dprint check
          pnpm biome check
      - name: API Check
        run: pnpm turbo api-extractor
      - name: has-changeset
        run: pnpm changeset status --since=origin/$GITHUB_BASE_REF
  no-confusion-check:
    runs-on: lynx-ubuntu-24.04-medium
    steps:
      - uses: actions/checkout@v4
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45.0.7
        with:
          files_ignore: |
            **/output/**
            **/*.min.js
            **/pnpm-lock.yaml
            packages/web-platform/web-tests/tests/**
            packages/webpack/*/test/**
            packages/webpack/css-extract-webpack-plugin/src/loader.ts
            packages/webpack/react-refresh-webpack-plugin/runtime/refresh.cjs
      - name: coolkiid/no-confusion
        uses: coolkiid/no-confusion-action@0.1.2
        with:
          include: ${{ steps.changed-files.outputs.all_changed_files }}
      - name: pupiltong/forked_ms_Inclusiveness_Analyzer
        uses: PupilTong/InclusivenessAnalyzer@1.1.0-alpha6
        with:
          include: ${{ steps.changed-files.outputs.all_changed_files }}
          failOnNonInclusiveTerm: true
          maxLineLength: 2000
