name: Lint PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

permissions:
  # Allow `amannn/action-semantic-pull-request` to read pull requests
  pull-requests: read

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: lynx-ubuntu-24.04-medium
    timeout-minutes: 10
    steps:
      # https://github.com/amannn/action-semantic-pull-request
      - uses: amannn/action-semantic-pull-request@7f33ba792281b034f64e96f4c0b5496782dd3b37 # v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          # Derived from https://github.com/commitizen/conventional-commit-types
          types: |
            fix
            feat
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            release
            security
          # Configure which scopes are allowed (newline-delimited).
          # These are regex patterns auto-wrapped in `^ $`.
          scopes: |
            ^(?![A-Z]).+$
          # Configure that a scope must always be provided.
          requireScope: false
          # Configure which scopes are disallowed in PR titles (newline-delimited).
          # For instance by setting the value below, `chore(release): ...` (lowercase)
          # and `ci(e2e,release): ...` (unknown scope) will be rejected.
          # These are regex patterns auto-wrapped in `^ $`.
          disallowScopes: |
            [A-Z]+
          # Configure additional validation for the subject based on a regex.
          ignoreLabels: |
            bot
