on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
      LHCI_GITHUB_APP_TOKEN:
        required: false
    inputs:
      runs-on:
        required: true
        type: string
      run:
        required: true
        type: string
      is-web:
        required: false
        type: boolean
        default: false
      codecov-flags:
        required: false
        type: string
        default: "unittest"

env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
jobs:
  check:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Codecov requires fetch-depth: 0
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: TurboCache
        uses: lynx-infra/cache@558d7c999f9f97ac02ed7e711503bb81d82ff8ee
        with:
          path: .turbo
          # We have to be strict here to make sure getting the cache of build-all
          key: turbo-v3-${{ hashFiles('**/packages/**/src/**/*.rs') }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Install
        run: |
          npm install -g corepack@latest
          corepack enable
          pnpm install --frozen-lockfile
      - name: Build
        run: |
          pnpm turbo build --summarize
      - uses: ./.github/actions/setup-playwright
        if: ${{ inputs.is-web }}
        with:
          working-directory: packages/web-platform/web-tests
      - name: Test
        id: test
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: ${{ inputs.run }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ inputs.codecov-flags }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ inputs.codecov-flags }}
      - name: Upload Test Result
        if: ${{ inputs.is-web && failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: packages/web-platform/web-tests/playwright-report
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true
