on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      run:
        required: true
        type: string
      is-web:
        required: false
        type: boolean
        default: false
env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
jobs:
  check:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Codecov requires fetch-depth: 0
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: TurboCache
        uses: actions/cache@v4
        with:
          path: .turbo
          # We have to be strict here to make sure getting the cache of build-all
          key: turbo-v3-${{ hashFiles('**/packages/**/src/**/*.rs') }}-${{ github.sha }}
      - name: Install
        run: |
          npm install -g corepack@latest
          corepack enable
          pnpm install --frozen-lockfile
      - name: Build
        run: |
          pnpm turbo build --summarize
      - name: Upload Turbo Summary
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: turbo-summary-${{ github.ref }}
          path: .turbo/runs
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true
      - uses: ./.github/actions/setup-playwright
        if: ${{ inputs.is-web }}
        with:
          working-directory: packages/web-platform/web-tests
      - name: Test
        id: test
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: ${{ inputs.run }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: inputs.is-web != 'true'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ inputs.is-web != 'true' && !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload Test Result
        if: ${{ inputs.is-web && failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: packages/web-platform/web-tests/playwright-report
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true
