name: Reusable Playwright
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
    inputs:
      runs-on:
        required: true
        type: string
      playwright-package:
        required: true
        type: string
      playwright-report-name:
        required: false
        type: string
        default: "playwright-report"
      playwright-report-path:
        required: false
        type: string
        default: "playwright-report"
      codecov-flags:
        required: false
        type: string
        default: "e2e"

env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
jobs:
  playwright:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          # Codecov requires fetch-depth: 0
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: "24"
          package-manager-cache: false
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1
        with:
          components: clippy, rustfmt
          cache: false
      - name: Install
        run: |
          npm install -g corepack@latest
          corepack enable
          pnpm install --frozen-lockfile
      - name: Install Playwright
        run: pnpm --filter @lynx-js/web-elements exec playwright install --with-deps chromium firefox webkit
      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=32768
        run: pnpm turbo build --summarize
      - name: Test
        id: test
        env:
          NODE_OPTIONS: --max-old-space-size=32768
          GITHUB_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLAYWRIGHT_JUNIT_OUTPUT_NAME: test-report.junit.xml
        run: |
          pnpm --filter "${{ inputs.playwright-package }}" run test --reporter='github,dot,junit,html'
          pnpm --filter "${{ inputs.playwright-package }}" run coverage:ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ inputs.codecov-flags }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3de # v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ inputs.codecov-flags }}
          override_branch: ${{ github.event_name == 'merge_group' && 'main' || '' }}
      - name: Upload Test Result
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ inputs.playwright-report-name }}
          path: ${{ inputs.playwright-report-path }}
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true
